export { Archive } from "./Archive/Archive";
export { Notes } from "./Notes/Notes";
export { Trash } from "./Trash/Trash";
export { Home } from "./Home/Home";
export { Login } from "./Authentication/Login/login";
export { Signup } from "./Authentication/Signup/signup";
export { NotFound } from "./NotFound/NotFound";
export { Labels } from "./Labels/Labels";
export { SingleLabel } from "./SingleLabel/SingleLabel";
